# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8871d5f58d106ddcbdeb44f58d9eb50630c1a608f08a20875e13e6861d2b383a1e52ebdf58153ada8b0749e78f725300a1b011bacc300a7a46390b00adf894d7

test:
  secret_key_base: 3ab9d1fec95e904f5c2aec9f2e745b79128861e287081ac89db054757398fb0d7b73aab99b2f974adc8097a14debe67879827cc9120a65f4a46423ef219a8cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
